###
# @name Reset
POST http://localhost:3000/reset
Content-Type: application/json

{ "account": "testMinus1",
    "balance": 125 }

###
# @name Charge
POST http://localhost:3000/charge
Content-Type: application/json

{
    "account": "testMinus1",
    "charges": 50
}